package com.capgemini.SearchAPI.entities;

import java.util.Date;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.capgemini.SearchAPI.beans.ShortTheater;

@DynamoDBTable(tableName = "Movies")
public class Movie {
	
	private	String movieId;
	private	String name;
	private	String genre;
	private	String duration;
	private	String movieDimension;
	private	Date dateReleased;
	private	List<String> casts;
	private	List<ShortTheater> theatres;
	private	List<String> languages;
	
	public Movie() {
		// Default Constructor
	}

	public Movie(String name, String genre, String duration, String movieDimension, Date dateReleased,
			List<String> casts, List<ShortTheater> theatres, List<String> languages) {
		super();
		this.name = name;
		this.genre = genre;
		this.duration = duration;
		this.movieDimension = movieDimension;
		this.dateReleased = dateReleased;
		this.casts = casts;
		this.theatres = theatres;
		this.languages = languages;
	}

	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	public String getMovieId() {
		return movieId;
	}

	public void setMovieId(String movieId) {
		this.movieId = movieId;
	}

	@DynamoDBAttribute
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@DynamoDBAttribute
	public String getGenre() {
		return genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	@DynamoDBAttribute
	public String getDuration() {
		return duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	@DynamoDBAttribute
	public String getMovieDimension() {
		return movieDimension;
	}

	public void setMovieDimension(String movieDimension) {
		this.movieDimension = movieDimension;
	}

	@DynamoDBAttribute
	public Date getDateReleased() {
		return dateReleased;
	}

	public void setDateReleased(Date dateReleased) {
		this.dateReleased = dateReleased;
	}

	@DynamoDBAttribute
	public List<String> getCasts() {
		return casts;
	}

	public void setCasts(List<String> casts) {
		this.casts = casts;
	}

	@DynamoDBAttribute
	public List<ShortTheater> getTheatres() {
		return theatres;
	}

	public void setTheatres(List<ShortTheater> theatres) {
		this.theatres = theatres;
	}

	@DynamoDBAttribute
	public List<String> getLanguages() {
		return languages;
	}

	public void setLanguages(List<String> languages) {
		this.languages = languages;
	}
	
}
